// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdlwjrdvjpnwhdvohyxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbHdqcmR2anBud2hkdm9oeXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjY3OTksImV4cCI6MjA2NDAwMjc5OX0.VseIHFpcit7mM1AeTaXh78xH0H4senWMQW91u5Grxls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);